stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - cd backend/book-service

build:
  stage: build
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/
    expire_in: 1 week

unit_test:
  stage: test
  script:
    - ./gradlew test -Dspring.profiles.active=unit --tests '*Test' --tests '!*IntegrationTest'
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
      coverage_report:
        coverage_format: cobertura
        path: build/reports/jacoco/test/html/index.html
    paths:
      - build/reports/tests/test/
      - build/test-results/test/
  coverage: '/Total.*?([0-9]{1,3})%/'

integration_test:
  stage: test
  services:
    - name: postgres:15
      alias: postgres
  variables:
    POSTGRES_DB: bookdb
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  script:
    - |
      echo "Waiting for PostgreSQL to be ready..."
      for i in {1..30}; do
        if pg_isready -h postgres -p 5432 -U postgres; then
          break
        fi
        sleep 1
      done
    - ./gradlew test -Dspring.profiles.active=test --tests '*IntegrationTest'
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
    paths:
      - build/reports/tests/test/
      - build/test-results/test/
  when: manual